
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '25 4 * * *'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  license:
    name: Check license header
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apache/skywalking-eyes/header@501a28d2fb4a9b962661987e50cf0219631b32ff
        with:
          config: .github/licenserc.yaml

  security:
    name: Audit security
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo-aduit
        run: cargo install cargo-audit --version 0.21.1 --locked
      - name: Audit dependencies
        run: cargo audit

  style:
    name: Audit style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      - name: Check format
        run: cargo fmt --all -- --check

  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Install mysql-client
        if: ${{ contains(matrix.os, 'macos') }}
        run: brew install mysql@8.4
      - run: cargo build --workspace
      - run: |
          export PATH="/opt/homebrew/opt/mysql@8.4/bin:$PATH"
          cargo test --workspace --all-features

  pass:
    name: All tests passed
    runs-on: ubuntu-latest
    needs:
      - security
      - style
      - test
    steps:
      - run: exit 0
